s = set()
n = input("enter number :")
s.add(int(n))
n = input("enter number :")
s.add(int(n))
n = input("enter number :")
s.add(int(n))
n = input("enter number :")
s.add(int(n))
n = input("enter number :")
s.add(int(n))
n = input("enter number :")
s.add(int(n))
n = input("enter number :")
s.add(int(n))
n = input("enter number :")
s.add(int(n))

print(s)
#here  we weite set() and after entering number from user ift will written only unique number means non repetative only occurs one time
