d = {}

name = input("enter friends name :")
lang = input("enter langauge name :")
d.update({name: lang})
name = input("enter friends name :")
lang = input("enter langauge name :")
d.update({name: lang})
name = input("enter friends name :")
lang = input("enter langauge name :")
d.update({name: lang})
name = input("enter friends name :")
lang = input("enter langauge name :")
d.update({name: lang})
print(d)
